---
title: "Symposium Speech"
date: 2025-02-22
draft: false
categories:
- Writing Sample
tags:
- Articles
---

* Introduction:
As a part of my freshman seminar class EHON 1151 our professor Scot Douglass ask us to come up with our own ideas regarding the concept of love and to share this with a small group of our peers over a home cooked dinner party, in the spirit of the events of /Symposium/ by Plato. I share a transcript of my speech below in which I share my idea regarding how one can distinguish between different types of love and critique over how love is commonly recognized modernly.

* Speech:
As recounted by Socrates, “According to Diotima, Love is not a god at all, but is rather a spirit that mediates between people and the objects of their desire. Love is neither wise nor beautiful, but is rather the desire for wisdom and beauty.” Oftentimes, many expect love to show up for them. As if it'll take the form of a wise and beautiful person that they'll happen to stumble upon. This mindset will result in one missing out on true love. Love is the act of desire, the intention and want of a person. In other words, love is the choice of the person, to choose to love and to practice love than to stumble upon love.

I love to eat pizza. I love my mom. And I love my mom's cooking. Whenever, I say these things I can always think of “why” I love these things and people. I can justify my love and through it's justification my love becomes understood. I wasn't randomly born with a predisposition to love these things. I hardly understood loving something when I was born. I only understand what I've experienced, and then I can only then derive opinions from my experiences. I might've been born to my mother but there is no true obligation to love her. I learned to love her. I learned I loved her because she fed me. I learned I loved her because she cared for me. And I learned I loved her because she wanted me to live. I chose to love her, based on what I learned, and that's what makes it more meaningful. Intention, meaning, and freedom are all things that make love the powerful and fulling force that it is. Your goals, your feelings, your actions, they mean something because you chose to act on them and you set them for yourself. Love is much in the same, you define it for yourself, and you choose who you love for youself so through yourself it's significance is made clear.

Love is not an act of waiting in desire. It is often espoused, “Love comes to those who wait,” and “You'll just know if they're the right one.” But observing modern gender expectations will show that these sayings are flat out fallacious. Obtaining the love of someone else requires that you yourself give them your love, or in other words, you open up to how you feel about them. As massive part of why so many romances are so tense is because there is often someone who simply wants to recieve love rather than to give love.

Classic disney movies are most well known vehicles for these outdated ideals. Princesses like Cinderella, Sleeping Beauty, and Snow White are the poster children for the passive helpless woman waiting for the heroic man to save the day. The relationships depeticed by these movies are presented as also being so perfect that it is not even a question that they'll last with “The End” signifying the events after the story don't matter because the relationship doesn't have a story. But, the most problematic part of their movies is that the movie frames the potagonist's passivity as the central and defining reason for such a perfect love exist by revolving the narration and story around the inactive protagonistic.

In reality, the godmother had to get Cinderella out of the house, the Prince had to be led by the dwarves to Snow White, someone had to write the prophecy to bring Sleeping Beauty her groom. There is a prevelant existence of effort required to bring the princess and her prince together and the lack of action on the princess's part always rings as odd and fairytale-like. Yet these movies are lifelike enough to convince that love should be like a fairytale and not something realistic and grounded.

The Beauty and the Beast yet deviates from this norm. The protagonist, Belle has much higher expectations for love rather as she rejects Gaston, someone she barely knows.  She is more intentional about who she wishes to love and why. Later, she meets the Beast, a prince turned ferocious monster, which should be someone she can't love. After all how could she love something so different and monsterous? But as the movie continues the prince learns to open up and Belle learns to love the Beast. They don't start off as people who complete and find each other. They have discord, arguments, and conflict. But none of that matters as the cooperate, learn, accept, and appreciate each other. They aren't seeking perfect love, they're building perfect love.

One thing people will argue is that even if you chose to love them that you still had encountered these people by the hand of chance. And as a result this random encounter is evidence of soulmates. That you were predetermined by fate to love these specific people. But “who and what” you love or “when and where” you love them are irrelevant details in evaluating love in comparision to “why and how” you love them.

I can love a multitude of different pizza slices. I can love cheese, I can love pepperoni, and I can love Chicago pizza. I can't love chocolate pizza, I can't love “dessert pizza”, and I can't love cheeseless pizza. I have a wide variety of different reasons for loving each pizza but I still love them all the same. I show my appreciation for pizza for eating them. Because I don't love the other pizzas I don't show my appreciation to them. I can't have a pizza soulmate because there are different reasons for why I love the pizza the same way. What kind of pizza I love is largely irrelevant because I love them in the same way and they all mean the same thing to me.

With people it's more complex. I love my mom, I love my friends, and I'd love to have a girlfriend... I love my mom for different reasons than I love my friends and in turn the reasons I'd love a girlfriend would also be different, and how I love them is also different is it not? I love my mom by hugging them and I hug some of my friends. I love my mom because she cares for me but I wouldn't be friends with my friends if they didn't care about me. It's still true I have different boundaries with how I love my friends and how I love my families, but it's still possible for me to express my love all in the same way and to love them both for the same reasons. I choose to show my love to them in different ways and acknowledge different reasons for loving them. But, that choice doesn't change that I can love all these people for the same reason and can love them all in the same ways. So does it not stand that it simply doesn't matter the “who” I am loving over the “why and how” I am loving?

“Love is not primarily a relationship to a specific person; it is an attitude, an orientation of character which determines the relatedness of a person to the world as a whole, not toward one “object” of love. If a person loves only one other person and is indifferent to the rest of his fellow men, his love is not love but a symbiotic attachment, or an enlarged egotism. Yet, most people believe that love is constituted by the object, not by the faculty.” - Eric Fromm,  Art of Loving.
